apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: de-pii-app
  namespace: de-pii
  labels:
    app.kubernetes.io/name: de-pii-app
    app.kubernetes.io/part-of: de-pii
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: de-pii-app
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
