apiVersion: v1
kind: Service
metadata:
  name: redactly-app
  namespace: redactly
  labels:
    app.kubernetes.io/name: redactly-app
    app.kubernetes.io/part-of: redactly
    app.kubernetes.io/component: app
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: redactly-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
