apiVersion: v1
kind: Service
metadata:
  name: de-pii-app
  namespace: de-pii
  labels:
    app.kubernetes.io/name: de-pii-app
    app.kubernetes.io/part-of: de-pii
    app.kubernetes.io/component: app
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: de-pii-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
